# Mini Project #4

#### 레드 와인 품질 예측

---

## 데이터셋 입력 및 라벨 분리

#### 데이터셋 불러오기


In [25]:
import numpy as np
import pandas as pd

input_file_name = "data/winequality-red.csv"
df_train = pd.read_csv(input_file_name)

#### 데이터셋 확인

In [30]:
df_train.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [28]:
df_train['quality'].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [29]:
df_train.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [33]:
df_train.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [34]:
for column in df_train.columns:
    mean = df_train[column].mean()
    std = df_train[column].std()
    outliers = df_train[(df_train[column] < mean - 3*std) | (df_train[column] > mean + 3*std)]
    print(f'{column} 이상치 개수: {len(outliers)}')

fixed acidity 이상치 개수: 12
volatile acidity 이상치 개수: 10
citric acid 이상치 개수: 1
residual sugar 이상치 개수: 30
chlorides 이상치 개수: 31
free sulfur dioxide 이상치 개수: 22
total sulfur dioxide 이상치 개수: 15
density 이상치 개수: 18
pH 이상치 개수: 8
sulphates 이상치 개수: 27
alcohol 이상치 개수: 8
quality 이상치 개수: 10


#### DataFrame 객체를 numpy 배열로 변환


In [14]:
np_data = df_train.to_numpy()
np_data

array([['fixed acidity', 'volatile acidity', 'citric acid', ...,
        'sulphates', 'alcohol', 'quality'],
       ['7.4', '0.7', '0.0', ..., '0.56', '9.4', '5'],
       ['7.8', '0.88', '0.0', ..., '0.68', '9.8', '5'],
       ...,
       ['6.3', '0.51', '0.13', ..., '0.75', '11.0', '6'],
       ['5.9', '0.645', '0.12', ..., '0.71', '10.2', '5'],
       ['6.0', '0.31', '0.47', ..., '0.66', '11.0', '6']], dtype=object)

#### 학습 셋과 라벨 분리

In [29]:
x_train = np_data[:, 1:]
# x_train

In [55]:
y_train = np_data[:, 0]
y_train

array([8, 9, 6, ..., 1, 1, 0])

## 데이터 전처리

#### Normalization

In [39]:
x_train = x_train / 255.0

#### label One Hot Encode

In [56]:
from sklearn.preprocessing import OneHotEncoder

OH_encoder = OneHotEncoder()
y_train_res = y_train.reshape(-1, 1)
y_train_encoded = OH_encoder.fit_transform(y_train_res).toarray()

array([8, 9, 6, ..., 1, 1, 0])

## 확률적 경사 하강법 분류기

In [57]:
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(max_iter=5, tol=None, random_state=42)
sgd_clf.fit(x_train, y_train)

SGDClassifier(max_iter=5, random_state=42, tol=None)

In [48]:
from sklearn.model_selection import cross_val_score

cross_val_score(sgd_clf, x_train, y_train, cv=10, scoring="accuracy")

/opt/homebrew/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Ple

array([0.92066667, 0.9195    , 0.91804167, 0.91754167, 0.9195    ,
       0.91554167, 0.92033333, 0.9245    , 0.92229167, 0.92108333])

In [49]:
np.mean([0.92066667, 0.9195    , 0.91804167, 0.91754167, 0.9195    ,
       0.91554167, 0.92033333, 0.9245    , 0.92229167, 0.92108333]
)

0.919900001